#!/usr/bin/env bash
# Scaffold a new private bare repo under $GIT_ROOT/repos/<name>.git.
#
# Usage:
#   new-repo.sh <name>                                    # repo only
#   new-repo.sh <name> <target-ip> <target-path>           # + auto-deploy on push to main
#
# Example:
#   new-repo.sh receipts 192.168.1.60 /opt/receipts
#
# Auto-deploy pushes files via rsync over SSH using the dedicated deploy key
# (see git-hosting-setup.sh) — it can ONLY write into <target-path> on the
# target machine (enforced by rrsync in the target's authorized_keys, see
# target-setup.sh). Nothing here ever needs root on the target beyond that
# one restricted key. The target restarts its own service automatically via
# a systemd .path unit — see target-setup.sh, which you run once ON the
# target.
set -euo pipefail

CONFIG=/etc/ai-dev-switchboard/git-hosting.env
[ -f "$CONFIG" ] && source "$CONFIG"
GIT_ROOT="${GIT_ROOT:-/srv/git}"
GIT_USER="${GIT_USER:-git}"
DEPLOY_KEY="${DEPLOY_KEY:-$GIT_ROOT/.ssh/deploy_ed25519}"
ADVERTISE_HOST="${ADVERTISE_HOST:-$(hostname -I 2>/dev/null | awk '{print $1}')}"

if [ $# -ne 1 ] && [ $# -ne 3 ]; then
    echo "Usage: $0 <name> [target-ip target-path]" >&2
    exit 1
fi

NAME="$1"
REPO="$GIT_ROOT/repos/${NAME}.git"

if [ -e "$REPO" ]; then
    echo "Already exists: $REPO" >&2
    exit 1
fi

su "$GIT_USER" -s /bin/bash -c "git init --bare '$REPO'" >/dev/null
su "$GIT_USER" -s /bin/bash -c "mkdir -p '$REPO/hooks'"

# Every post-receive hook here (this deploy block, and any block
# new-dev-instance.sh appends later) reads ref updates from a cached copy of
# stdin rather than stdin directly — stdin can only be consumed once, so two
# independent `while read` loops in the same hook would otherwise silently
# starve the second one of input.
su "$GIT_USER" -s /bin/bash -c "cat > '$REPO/hooks/post-receive'" <<'PREAMBLE'
#!/usr/bin/env bash
set -euo pipefail
_STDIN_CACHE=$(mktemp)
trap 'rm -f "$_STDIN_CACHE"' EXIT
cat > "$_STDIN_CACHE"
PREAMBLE

if [ $# -eq 3 ]; then
    TARGET_IP="$2"
    TARGET_PATH="$3"

    su "$GIT_USER" -s /bin/bash -c "cat >> '$REPO/hooks/post-receive'" <<HOOK

# Auto-deploy: on push to main, rsync the checked-out tree to
# deploy@${TARGET_IP}:${TARGET_PATH}. Generated by new-repo.sh — edit freely.
KEY=${DEPLOY_KEY}

while read -r oldrev newrev refname; do
    branch=\$(git rev-parse --symbolic --abbrev-ref "\$refname")
    if [ "\$branch" != "main" ]; then
        echo "post-receive: skipping non-main branch '\$branch'"
        continue
    fi
    TMP=\$(mktemp -d)
    chmod 755 "\$TMP"  # mktemp defaults to 700; rsync -a would carry that onto
                       # the deployed dir itself and lock out the service user
    git --work-tree="\$TMP" --git-dir="${REPO}" checkout -f main
    date -u +%FT%TZ > "\$TMP/.deployed"
    # NOTE: no path after the colon — rrsync on the target already restricts
    # writes to its configured DIR (see target-setup.sh) and prefixes that
    # DIR to anything the client sends, so a client-side path here would
    # double up (e.g. DIR/DIR) and fail.
    rsync -az --delete -e "ssh -i \$KEY -o StrictHostKeyChecking=accept-new -o BatchMode=yes" \\
        "\$TMP"/ "deploy@${TARGET_IP}:"
    rm -rf "\$TMP"
    echo "post-receive: synced to ${TARGET_IP}:${TARGET_PATH} — target restarts itself"
done < "\$_STDIN_CACHE"
HOOK
    su "$GIT_USER" -s /bin/bash -c "chmod +x '$REPO/hooks/post-receive'"
    echo "Created $REPO (auto-deploy -> ${TARGET_IP}:${TARGET_PATH})"
    echo ""
    echo "Still needed ONCE on the target machine (run target-setup.sh there):"
    echo "  target-setup.sh ${TARGET_PATH} <systemd-service-name> \"$(cat "$GIT_ROOT/.ssh/deploy_ed25519.pub" 2>/dev/null || echo '<see git-hosting-setup.sh output>')\""
else
    su "$GIT_USER" -s /bin/bash -c "chmod +x '$REPO/hooks/post-receive'"
    echo "Created $REPO (no auto-deploy — rerun with target-ip + target-path, or add hooks/post-receive by hand)"
fi

echo ""
echo "Remote for this repo:"
echo "  git remote add dev ssh://${GIT_USER}@${ADVERTISE_HOST}${REPO}"
echo "  git push dev main"
